export const careersConstants = {
	GET_CREERS_LIST_SUCCESS: 'CREERS_SUCCESS',
	GET_CREERS_LIST_FAILURE: 'CREERS_FAILURE',
	GET_DESCRIPTION_SUCCESS: 'DESCRIPTION_SUCCESS',
	GET_DESCRIPTION_FAILURE: 'DESCRIPTION_FAILURE'
};
