export const resetPasswordConstants = {
  RESET_PASSWORD_EMAIL_SUCCESS: 'RESET_PASSWORD_EMAIL_SUCCESS',
  RESET_PASSWORD_EMAIL_FAILURE: 'RESET_PASSWORD_EMAIL_FAILURE',
  REST_Password_SUCCESS: 'REST_Password_SUCCESS',
  REST_Password_FAILURE: 'REST_Password_FAILURE',
};
